# Generated by Django 5.0 on 2023-12-09 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
