# Generated by Django 5.0 on 2023-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care", "0005_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="basic_plan",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="plan_names",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="platinum_plan",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="premium_plan",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="standard_plan",
        ),
        migrations.AddField(
            model_name="plan",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
