# Generated by Django 5.0 on 2023-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care", "0006_remove_plan_basic_plan_remove_plan_plan_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
